### ISSUE TITLE
Blocky's Hooker is writing wrong section.START values to the compressed file

### ISSUE THREAD

**Issue by ghost** [SimuPoLAS/blocky#23]
a quick test revealed that decompression isn't misinterpreting the section.START values, but rather that Blocky's Hooker is writing wrong section.START values to the file. the first section is right, but the second section has a START value of ~1900, whereas Ofc has a START value of ~1200 for it's second section. 

this is a critical issue, as it's rendering blockydecompression dysfunctional by not giving it the value it needs to know

plz send help

**Comment by satorialist** [comment]
as it turns out, Ofc has a START value of 886 for the first section, whereas blocky has a START value of 864. this is alright as Ofc uses Windows line endings (NL CR), which is one more character than UNIX uses (NL). this accounts for the missing 22 bytes, as alpha.water has exactly 22 lines before the first section. 

the second section however is still wrong
pls fix

**Comment by satorialist** [comment]
after further investigation, we came to the conclusion, that the END value as is saved in the Hooker of the first section is faulty.

**Comment by satorialist** [comment]
with the help of the almighty @UgiNyaa, this issue was resolved. it turned out that the Hooker didn't have updated providedPosition values, which in turn led to wrong END values.
